import type { Config } from 'tailwindcss';

export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
      },
      backgroundImage: {
        '101B': "url('/card-images/blue_11.webp')",
        '102B': "url('/card-images/blue_12.webp')",
        '103B': "url('/card-images/blue_11.webp')",
        '104B': "url('/card-images/blue_12.webp')",
        '105B': "url('/card-images/blue_11.webp')",
        '106B': "url('/card-images/blue_12.webp')",
        '107B': "url('/card-images/blue_11.webp')",
        '108B': "url('/card-images/blue_12.webp')",
        '109G': "url('/card-images/green_11.webp')",
        '110G': "url('/card-images/green_12.webp')",
        '111G': "url('/card-images/green_11.webp')",
        '112G': "url('/card-images/green_12.webp')",
        '113G': "url('/card-images/green_11.webp')",
        '114G': "url('/card-images/green_12.webp')",
        '115G': "url('/card-images/green_11.webp')",
        '116G': "url('/card-images/green_12.webp')",
        '117K': "url('/card-images/black_11.webp')",
        '118K': "url('/card-images/black_12.webp')",
        '119K': "url('/card-images/black_11.webp')",
        '120K': "url('/card-images/black_12.webp')",
        '121K': "url('/card-images/black_11.webp')",
        '122K': "url('/card-images/black_12.webp')",
        '123K': "url('/card-images/black_11.webp')",
        '124K': "url('/card-images/black_12.webp')",
        '125R': "url('/card-images/red_11.webp')",
        '126R': "url('/card-images/red_12.webp')",
        '127R': "url('/card-images/red_11.webp')",
        '128R': "url('/card-images/red_12.webp')",
        '129R': "url('/card-images/red_11.webp')",
        '130R': "url('/card-images/red_12.webp')",
        '131R': "url('/card-images/red_11.webp')",
        '132R': "url('/card-images/red_12.webp')",
        '133W': "url('/card-images/white_11.webp')",
        '134W': "url('/card-images/white_12.webp')",
        '135W': "url('/card-images/white_11.webp')",
        '136W': "url('/card-images/white_12.webp')",
        '137W': "url('/card-images/white_11.webp')",
        '138W': "url('/card-images/white_12.webp')",
        '139W': "url('/card-images/white_11.webp')",
        '140W': "url('/card-images/white_12.webp')",
        '201B': "url('/card-images/blue_21.webp')",
        '202B': "url('/card-images/blue_22.webp')",
        '203B': "url('/card-images/blue_21.webp')",
        '204B': "url('/card-images/blue_22.webp')",
        '205B': "url('/card-images/blue_21.webp')",
        '206B': "url('/card-images/blue_22.webp')",
        '207G': "url('/card-images/green_21.webp')",
        '208G': "url('/card-images/green_22.webp')",
        '209G': "url('/card-images/green_21.webp')",
        '210G': "url('/card-images/green_22.webp')",
        '211G': "url('/card-images/green_21.webp')",
        '212G': "url('/card-images/green_22.webp')",
        '213K': "url('/card-images/black_21.webp')",
        '214K': "url('/card-images/black_22.webp')",
        '215K': "url('/card-images/black_21.webp')",
        '216K': "url('/card-images/black_22.webp')",
        '217K': "url('/card-images/black_21.webp')",
        '218K': "url('/card-images/black_22.webp')",
        '219R': "url('/card-images/red_21.webp')",
        '220R': "url('/card-images/red_22.webp')",
        '221R': "url('/card-images/red_21.webp')",
        '222R': "url('/card-images/red_22.webp')",
        '223R': "url('/card-images/red_21.webp')",
        '224R': "url('/card-images/red_22.webp')",
        '225W': "url('/card-images/white_21.webp')",
        '226W': "url('/card-images/white_22.webp')",
        '227W': "url('/card-images/white_21.webp')",
        '228W': "url('/card-images/white_22.webp')",
        '229W': "url('/card-images/white_21.webp')",
        '230W': "url('/card-images/white_22.webp')",
        '301B': "url('/card-images/blue_31.webp')",
        '302B': "url('/card-images/blue_32.webp')",
        '303B': "url('/card-images/blue_31.webp')",
        '304B': "url('/card-images/blue_32.webp')",
        '305G': "url('/card-images/green_31.webp')",
        '306G': "url('/card-images/green_32.webp')",
        '307G': "url('/card-images/green_31.webp')",
        '308G': "url('/card-images/green_32.webp')",
        '309K': "url('/card-images/black_31.webp')",
        '310K': "url('/card-images/black_32.webp')",
        '311K': "url('/card-images/black_31.webp')",
        '312K': "url('/card-images/black_32.webp')",
        '313R': "url('/card-images/red_31.webp')",
        '314R': "url('/card-images/red_32.webp')",
        '315R': "url('/card-images/red_31.webp')",
        '316R': "url('/card-images/red_32.webp')",
        '317W': "url('/card-images/white_31.webp')",
        '318W': "url('/card-images/white_32.webp')",
        '319W': "url('/card-images/white_31.webp')",
        '320W': "url('/card-images/white_32.webp')",
        NB01: "url('/noble-images/noble_01.webp')",
        NB02: "url('/noble-images/noble_02.webp')",
        NB03: "url('/noble-images/noble_03.webp')",
        NB04: "url('/noble-images/noble_04.webp')",
        NB05: "url('/noble-images/noble_05.webp')",
        NB06: "url('/noble-images/noble_06.webp')",
        NB07: "url('/noble-images/noble_07.webp')",
        NB08: "url('/noble-images/noble_08.webp')",
        NB09: "url('/noble-images/noble_09.webp')",
        NB10: "url('/noble-images/noble_10.webp')",
      },
    },
  },
  plugins: [require('@designbycode/tailwindcss-text-stroke')],
} satisfies Config;
